import 'bootstrap/dist/css/bootstrap.css';
import "./globals.css";
import "./page.css";
import { Inter } from "next/font/google";
import Header from "./header.js";
import Footer from "./footer.js";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div class="container">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}